Repository Memento-Makers/Emopic-BE, pull requests merged in 2023-10, with the labels that each got.

#43 [feat] 사진 전체 정보 조회 기능 추가
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotosInformationResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/SignedURLGenerator.java
Labels: 🌟 feature

#45 ✨feat: signed_url 재생성 코드 작성
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/SignedURLScheduler.java
  emopic/src/main/resources/application.yml
Labels: 🌟 feature

#47 [feat] 백 이미지 업로드 기능 구현
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryController.java
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/request/PhotoUploadRequest.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotoUploadResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotosInformationResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/ImageUploader.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/PhotoInferenceWithAI.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/SignedURLGenerator.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/SignedURLScheduler.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/Translators.java
  emopic/src/main/resources/application-dev.yml
  emopic/src/main/resources/application-prod.yml
  emopic/src/main/resources/application.yml
Labels: 🌟 feature

#51 update: 전체 페이지 API 페이지네이션 반환 객체 수정, signed_url 재생성하는 코드 제거 (스케줄러로 대체)…
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PageResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
Labels: 🌟 feature

#52 [feat] 장소 관련 기능 개발, 기타 버그 수정
  emopic/build.gradle
  emopic/gradlew
  emopic/src/main/java/mmm/emopic/app/domain/emotion/Emotion.java
  emopic/src/main/java/mmm/emopic/app/domain/location/Location.java
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationRepository.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/KakaoCoord2regionResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/CategoryInferenceResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/ImageUploader.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/KakaoMapAPI.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/MetadataExtractor.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/PhotoInferenceWithAI.java
  emopic/src/main/resources/application-dev.yml
  emopic/src/main/resources/application-prod.yml
  emopic/src/main/resources/application.yml
Labels: 🐛 bug, 📄 docs, 🌟 feature

#57 [feat] 장소 관련 API 개발, 기타 업데이트
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationController.java
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationService.java
  emopic/src/main/java/mmm/emopic/app/domain/location/dto/response/LocationPhotoResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/location/dto/response/LocationPointResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/location/dto/response/LocationRecentResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PageResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/KakaoMapAPI.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/MetadataExtractor.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/PhotoInferenceWithAI.java
Labels: 🔧 chore, 🌟 feature

#58 update: page 반환객체 수정
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PageResponse.java
Labels: 🔧 chore

#61 지역별 대표(최근) 사진 조회 API
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationController.java
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationService.java
  emopic/src/main/java/mmm/emopic/app/domain/location/dto/response/CityResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/location/dto/response/LocationPointResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
Labels: 🌟 feature
