Repository Memento-Makers/Emopic-BE, pull requests merged in 2023-09, with the labels that each got.

#29 [docs] swagger 문서 생성 라이브러리 추가 및 설정
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/config/SwaggerConfig.java
  emopic/src/main/resources/application-dev.yml
  emopic/src/main/resources/application-prod.yml
  emopic/src/main/resources/application.yml
Labels: 🐛 bug, 📄 docs

#30 [docs] swagger 문서 내용 작성
  emopic/src/main/java/mmm/emopic/app/auth/AuthController.java
  emopic/src/main/java/mmm/emopic/app/auth/member/MemberController.java
  emopic/src/main/java/mmm/emopic/app/auth/member/support/CurrentUser.java
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryController.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/DiaryController.java
  emopic/src/main/java/mmm/emopic/app/domain/emotion/EmotionController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
Labels: 📄 docs

#26 [feat] dateTime Meta데이터 받아오는 기능 추가
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotoInformationResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/CategoryInferenceResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/PhotoInferenceWithAI.java
Labels: 🌟 feature

#32 [refactor] Pagenation 기능 snapped_at 기준으로 정렬
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
Labels: 🔨 refactor

#33 [refactor] : 비어있는 컬럼 내용 채우기
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryService.java
  emopic/src/main/java/mmm/emopic/app/domain/category/dto/response/CategoryDetailResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/Diary.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
Labels: 🔨 refactor

#31 [env] cors 설정 추가
  emopic/src/main/java/mmm/emopic/config/SecurityConfig.java
  emopic/src/main/resources/application-dev.yml
  emopic/src/main/resources/application-prod.yml
  emopic/src/main/resources/application.yml
Labels: 🐛 bug

#34 [faet] diary 내용 조회하는 기능 추가
  emopic/src/main/java/mmm/emopic/app/domain/diary/DiaryController.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/DiaryService.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/dto/request/DiarySaveRequest.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/dto/response/DiaryGetResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/dto/response/DiarySaveResponse.java
Labels: 🌟 feature

#36 [refactor] 감정 저장 반환값 변경
  emopic/src/main/java/mmm/emopic/app/domain/emotion/EmotionService.java
Labels: 🔨 refactor

#37 [refactor] diaryContent 반환 수정
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotoInformationResponse.java
Labels: 🔨 refactor

#38 [feat] signedUrl 재생성 기능 추가
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/SignedURLGenerator.java
Labels: 🌟 feature

#39 [feat] classification 번역기 변경
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/DeeplTranslator.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/Translators.java
  emopic/src/main/resources/application.yml
Labels: 🌟 feature
