Repository Memento-Makers/Emopic-BE, pull requests merged in 2023-08, with the labels that each got.

#3 🔧env: google checkstyle 및 formatter setup
  emopic/build.gradle
  emopic/intellij-java-google-style.xml
  emopic/src/main/resources/checkstyle/google_checks.xml
Labels: 🌟 feature

#6 feat: SignedUrl 생성 api 개발
  emopic/.gitignore
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/EmopicApplication.java
  emopic/src/main/java/mmm/emopic/app/base/BaseEntity.java
  emopic/src/main/java/mmm/emopic/app/base/Dto/BaseResponse.java
  emopic/src/main/java/mmm/emopic/app/base/Dto/SavedId.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoRepository.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/PhotoUploadRequest.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/PhotoUploadResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/SignedURLGenerator.java
  emopic/src/main/resources/application.properties
  emopic/src/main/resources/application.yml
Labels: 🌟 feature

#17 [feat] Category별 분류 결과 조회 API 개발
  emopic/src/main/java/mmm/emopic/app/domain/category/Category.java
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryController.java
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryService.java
  emopic/src/main/java/mmm/emopic/app/domain/category/PhotoCategory.java
  emopic/src/main/java/mmm/emopic/app/domain/category/dto/request/CategoryRequest.java
  emopic/src/main/java/mmm/emopic/app/domain/category/dto/response/CategoryDetailResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/category/dto/response/CategoryResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/category/repository/CategoryRepository.java
  emopic/src/main/java/mmm/emopic/app/domain/category/repository/CategoryRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/category/repository/CategoryRepositoryImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/category/repository/PhotoCategoryRepository.java
Labels: 🌟 feature

#13 [✨feat] 인증 API 개발
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/app/auth/AuthController.java
  emopic/src/main/java/mmm/emopic/app/auth/AuthService.java
  emopic/src/main/java/mmm/emopic/app/auth/Dto/LoginRequest.java
  emopic/src/main/java/mmm/emopic/app/auth/Dto/TokenResponse.java
  emopic/src/main/java/mmm/emopic/app/auth/member/Dto/MemberResponse.java
  emopic/src/main/java/mmm/emopic/app/auth/member/Dto/RegisterRequest.java
  emopic/src/main/java/mmm/emopic/app/auth/member/Member.java
  emopic/src/main/java/mmm/emopic/app/auth/member/MemberController.java
  emopic/src/main/java/mmm/emopic/app/auth/member/MemberRepository.java
  emopic/src/main/java/mmm/emopic/app/auth/member/service/MemberDetailService.java
  emopic/src/main/java/mmm/emopic/app/auth/member/service/MemberService.java
  emopic/src/main/java/mmm/emopic/app/auth/member/support/CurrentUser.java
  emopic/src/main/java/mmm/emopic/app/auth/member/support/PrincipalDetails.java
  emopic/src/main/java/mmm/emopic/app/auth/member/support/Provider.java
  emopic/src/main/java/mmm/emopic/app/auth/member/support/Role.java
  emopic/src/main/java/mmm/emopic/app/auth/refreshToken/RefreshToken.java
  emopic/src/main/java/mmm/emopic/app/auth/refreshToken/RefreshTokenRepository.java
  emopic/src/main/java/mmm/emopic/app/auth/support/JwtTokenProvider.java
  emopic/src/main/java/mmm/emopic/app/exception/auth/PasswordMismatchException.java
  emopic/src/main/java/mmm/emopic/app/exception/auth/TokenNotValidException.java
  emopic/src/main/java/mmm/emopic/app/exception/base/BadRequestException.java
  emopic/src/main/java/mmm/emopic/app/exception/base/UnAuthorizedException.java
  emopic/src/main/java/mmm/emopic/app/exception/member/DuplicateUserIdException.java
  emopic/src/main/java/mmm/emopic/config/JwtFilter.java
  emopic/src/main/java/mmm/emopic/config/SecurityConfig.java
  emopic/src/main/resources/application.yml
Labels: 🌟 feature

#22 [refactor] diary 반환값 Optional로 변환
  emopic/src/main/java/mmm/emopic/app/domain/diary/Diary.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/DiaryService.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/repository/DiaryRepository.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotoInformationResponse.java
Labels: 🔨 refactor

#24 [feat] AI Inference 결과 번역 기능 추가
  emopic/build.gradle
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryController.java
  emopic/src/main/java/mmm/emopic/app/domain/category/CategoryService.java
  emopic/src/main/java/mmm/emopic/app/domain/emotion/EmotionService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoController.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/DeeplTranslator.java
  emopic/src/main/resources/application.yml
Labels: 🌟 feature

#25 [Deploy] github action 배포환경 구축
  .github/workflows/dev-publish.yml
  emopic/build.gradle
  emopic/dockerfile
  emopic/src/main/resources/application-dev.yml
  emopic/src/main/resources/application-prod.yml
Labels: 📦 build
