Repository Memento-Makers/Emopic-BE, pull requests merged in 2023-11, with the labels that each got.

#63 feat: 지역별 전체 사진 조회 API 개발 #62
  emopic/src/main/java/mmm/emopic/app/domain/category/repository/CategoryRepositoryImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationController.java
  emopic/src/main/java/mmm/emopic/app/domain/location/LocationService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/Photo.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/PhotoService.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotoInformationResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/dto/response/PhotosInformationResponse.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustom.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/repository/PhotoRepositoryCustomImpl.java
  emopic/src/main/java/mmm/emopic/app/domain/photo/support/MetadataExtractor.java
Labels: 🌟 feature

#65 Contributing Guide 추가
  README.md
Labels: 📄 docs

#66 update: diary 조회 API에 caption 내용 반환하는 필드 추가
  emopic/src/main/java/mmm/emopic/app/domain/diary/DiaryService.java
  emopic/src/main/java/mmm/emopic/app/domain/diary/dto/response/DiaryGetResponse.java
Labels: 🔧 chore
